import { useState } from "react";

// Head

import Head from "next/head";

// Styles

import styles from "@/styles/Home.module.css";
import stylesCardContent from "@/styles/CardContent.module.css";

// Font

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Components

import Card from "@/components/Card";
import CardHeader from "@/components/CardHeader";
import CardDescription from "@/components/CardDescription";
import CardContent from "@/components/CardContent";
import CardFooter from "@/components/CardFooter";
import CustomButton from "@/components/CustomButton";

export default function Home() {
  const [count, setCount] = useState(0);

  const increment = () => setCount((prev) => prev + 1);
  const decrement = () => setCount((prev) => (prev > 0 ? prev - 1 : 0));
  const reset = () => setCount(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Card>
          <CardHeader variant="blue">Compteur</CardHeader>
          <CardDescription variant="grey">
            Cliquez pour incrémenter
          </CardDescription>
          <CardContent>
            <span className={stylesCardContent.span}>{count}</span>
          </CardContent>
          <CardFooter>
            <CustomButton onClick={increment}>Incrementer</CustomButton>
            <CustomButton onClick={decrement}>Decrementer</CustomButton>
            <CustomButton onClick={reset}>Reset</CustomButton>
          </CardFooter>
        </Card>
      </main>
    </>
  );
}
